defaults: &defaults
  type_id:
    absence: 1
    overtime: 2
    annual_leave: 3
    sick: 4
  role_id:
    admin: 1
    root: 2
    normal_user: 3

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults